export const USER_LOGIN = 'USER_LOGIN' // 用户登录
export const RECEIVE_DATA = 'RECEIVE_DATA' // 准备数据
export const TOGGLE_COLUMN = 'TOGGLE_COLUMN'
export const CHANGE_ACTIVE = 'CHANGE_ACTIVE' // 点击顶部导航栏切换主页面
export const SHOW_LIST_DETAILS = 'SHOW_LIST_DETAILS' // 显示歌单内容
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LISTCHANGE_PLAY_LIST' // 显示歌单内容
export const STOP_PLLAY = 'STOP_PLLAY' // 播放暂停
export const NEXT_SONG = 'NEXT_SONG' // 换曲 (换音乐)
export const CLEAR_LIST = 'CLEAR_LIST' // 换曲 (换音乐)
export const SIMILARITY_MV = 'SIMILARITY_MV' // 相关MV
export const SHOW_LIST_MSG = 'SHOW_LIST_MSG' // 显示歌单信息
export const SHOW_ALL_SEARCH = 'SHOW_ALL_SEARCH' // 显示全网搜索
export const SHOW_LIST_SEARCH = 'SHOW_LIST_SEARCH'// 显示歌单内搜索框
export const SEARCH_HISROTY = 'SEARCH_HISROTY' // 记录搜索内容
export const CLEAR_SEARCH_HISROTY = 'CLEAR_SEARCH_HISROTY' // 清除历史记录
export const SHOWPLAYVIEW = 'SHOWPLAYVIEW' // 显示播放列表
export const CHANGE_PLAYING = 'CHANGE_PLAYING' // 改变当前播放歌曲
export const CLEARPLAYLIST = 'CLEARPLAYLIST' // 清空正在播放列表
export const SHOW_TOP_LIST = 'SHOW_TOP_LIST' // 清空正在播放列表
export const SHOW_BOUTIQUE_LIST = 'SHOW_BOUTIQUE_LIST' // 显示精品歌单
export const SHOW_DAY_RECOMMEND = 'SHOW_DAY_RECOMMEND' // 显示每日推荐歌曲
